
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use direct values for Supabase connection
const SUPABASE_URL = "https://vkuhnmamnhsakgontnfp.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdWhubWFtbmhzYWtnb250bmZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjYwOTEsImV4cCI6MjA2Mjc0MjA5MX0.H12zj2qjMyrXiv6BPkJ8B2gw2AnNTrHAE-LgXNtZUqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
